# version string format -- This will be overwritten later anyway
version: "{build}"

environment:
  MSVC_DEFAULT_OPTIONS: ON

os:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf input
  # Set build version to git commit-hash
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

# This allows us to pass %PLATFORM% to CMake -A.
platform:
  - x64

# build Configurations, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

#Cmake will autodetect the compiler, but we set the arch
before_build:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - cmake -H. -BBuild -A%PLATFORM%

# build with MSBuild
build:
  project: Build\CPPBoilerplate.sln   # path to Visual Studio solution or project
  parallel: true                        # enable MSBuild parallel builds
  verbosity: normal                     # MSBuild verbosity level {quiet|minimal|normal|detailed}

test_script:
  - cd Build
  - ctest -V -j 2 -C %CONFIGURATION%

